CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(100) NOT NULL,
    email VARCHAR(320),
    nickname VARCHAR(50),
    name VARCHAR(50),
    birth_date DATE,
    phone VARCHAR(20),
    phone_verified_at TIMESTAMP WITH TIME ZONE,
    residence_region_id BIGINT,
    military_months INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_app_user_auth_provider_provider_user_id UNIQUE (auth_provider, provider_user_id)
);
